version: '2'

services:
  web: 
    build: .
    ports:
      - "80:80"
    extends:
      file: common.yml
      service: common
  db:
    image: "mysql:5"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - /Users/jamlee/box/laravel/config/mysql:/etc/mysql/conf.d
    environment:
      - "MYSQL_ROOT_PASSWORD=jamlee"
      - "MYSQL_DATABASE=laravel"
  redis:
    image: "redis"
    ports:
      - "6379:6379"

volumes:
  dbdata:
